name: Fortify AST Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2.3.4  # Use a specific version

    - name: Run Fortify SCA
      run: |
        # Your Fortify SCA commands here
        # Add error handling if necessary
        set -e
        fortify-sca-command

    - name: Upload Fortify Results
      uses: actions/upload-artifact@v4
      with:
        name: fortify-results
        path: path/to/fortify/results  # Ensure this path is correct
