name: Ruby Gem

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build + Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby 2.6
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.x

      - name: Publish to GitHub Packages
        run: |
          mkdir -p $HOME/.gem
          echo '---\n:github: Bearer ${{secrets.GITHUB_TOKEN}}\n' > $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          gem build *.gemspec
          gem push --key github --host https://rubygems.pkg.github.com/${{ github.repository_owner }} *.gem
        env:
          GEM_HOST_API_KEY: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to RubyGems
        run: |
          mkdir -p $HOME/.gem
          echo '---\n:rubygems_api_key: ${{ secrets.RUBYGEMS_AUTH_TOKEN }}\n' > $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          gem build *.gemspec
          gem push *.gem
        env:
          GEM_HOST_API_KEY: ${{ secrets.RUBYGEMS_AUTH_TOKEN }}
